version: '3.8'
services:
  api:
    build: .
    depends_on:
      - adminer
    container_name: nestjs
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 3000:3000
    restart: always

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    depends_on:
      - db

networks:
  nest:
